#!/bin/bash
ip_new=`curl -s checkip.dyndns.org|sed -e 's/.*Current IP Address: //' -e 's/<.*$//'`

ip_original=`cat /root/scripts/network/ip.txt`

if [[ "$ip_original" != "$ip_new" && -n "$ip_new"  ]]
then
/root/scripts/network/mailip
fi
