#!/bin/bash

ip_new=`curl -s http://ipecho.net/plain;`

ip_original=`cat /root/scripts/network/ip.txt`

echo $ip_new > ip.txt

if [[ "$ip_original" != "$ip_new" && -n "$ip_new"  ]]
then
/root/scripts/network/mailip
fi
